/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.event.TableModelEvent;
import javax.swing.table.AbstractTableModel;
import projekt.DatabaseManager;

/**
 *
 * @author Tomek
 */
public class MainWindow extends javax.swing.JFrame
{
    private static AbstractTableModel model;
    private static DatabaseManager db;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(DatabaseManager db)
    {
        this.db = db;
        this.model = new Model();
        initComponents();
        setVisible(true);
        table.setDefaultRenderer(String.class, new MultiLineCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        resultPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        selectPanel = new javax.swing.JPanel();
        bookTitleButton = new javax.swing.JButton();
        bookLabel = new javax.swing.JLabel();
        articleLabel = new javax.swing.JLabel();
        readerLabel = new javax.swing.JLabel();
        bookAuthorButton = new javax.swing.JButton();
        articleTitleButton = new javax.swing.JButton();
        articleAuthorButton = new javax.swing.JButton();
        readerButton = new javax.swing.JButton();
        field = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        borrowButton = new javax.swing.JButton();
        QueryLabel = new javax.swing.JLabel();
        explanationLabel = new javax.swing.JLabel();
        okNotOk = new javax.swing.JLabel();
        optionsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(model);
        table.setToolTipText("");
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        bookTitleButton.setText("Search with title");
        bookTitleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bookTitleButtonActionPerformed(evt);
            }
        });

        bookLabel.setText("Books");

        articleLabel.setText("Articles");

        readerLabel.setText("Readers");

        bookAuthorButton.setText("Search with author");
        bookAuthorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bookAuthorButtonActionPerformed(evt);
            }
        });

        articleTitleButton.setText("Search with title");
        articleTitleButton.setToolTipText("");
        articleTitleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                articleTitleButtonActionPerformed(evt);
            }
        });

        articleAuthorButton.setText("Search with author");
        articleAuthorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                articleAuthorButtonActionPerformed(evt);
            }
        });

        readerButton.setText("Search with ID");
        readerButton.setToolTipText("");
        readerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                readerButtonActionPerformed(evt);
            }
        });

        field.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fieldActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                returnButtonActionPerformed(evt);
            }
        });

        borrowButton.setText("Borrow");
        borrowButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                borrowButtonActionPerformed(evt);
            }
        });

        QueryLabel.setText("Query:");

        explanationLabel.setText("reader ID. book ID");

        okNotOk.setText(" ");

        javax.swing.GroupLayout selectPanelLayout = new javax.swing.GroupLayout(selectPanel);
        selectPanel.setLayout(selectPanelLayout);
        selectPanelLayout.setHorizontalGroup(
            selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QueryLabel)
                .addGap(30, 30, 30)
                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectPanelLayout.createSequentialGroup()
                        .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(okNotOk))
                    .addGroup(selectPanelLayout.createSequentialGroup()
                        .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookLabel)
                            .addComponent(bookAuthorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(explanationLabel)
                            .addGroup(selectPanelLayout.createSequentialGroup()
                                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(borrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(articleLabel)
                                    .addComponent(articleTitleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(articleAuthorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(readerLabel)
                                    .addComponent(readerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        selectPanelLayout.setVerticalGroup(
            selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookLabel)
                    .addComponent(articleLabel)
                    .addComponent(readerLabel))
                .addGap(18, 18, 18)
                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitleButton)
                    .addComponent(articleTitleButton)
                    .addComponent(readerButton)
                    .addComponent(returnButton))
                .addGap(18, 18, 18)
                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAuthorButton)
                    .addComponent(articleAuthorButton)
                    .addComponent(borrowButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(explanationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QueryLabel)
                    .addComponent(okNotOk)))
        );

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTitleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bookTitleButtonActionPerformed
    {//GEN-HEADEREND:event_bookTitleButtonActionPerformed
        this.model = new BookModel(db.findBookWithTitle(this.field.getText().toUpperCase()));
        table.setModel(model);
        clear();
    }//GEN-LAST:event_bookTitleButtonActionPerformed

    private void bookAuthorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bookAuthorButtonActionPerformed
    {//GEN-HEADEREND:event_bookAuthorButtonActionPerformed
        this.model = new BookModel(db.findBooksWithAuthor(this.field.getText().toUpperCase()));
        table.setModel(model);
        clear();
    }//GEN-LAST:event_bookAuthorButtonActionPerformed

    private void articleTitleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_articleTitleButtonActionPerformed
    {//GEN-HEADEREND:event_articleTitleButtonActionPerformed
        this.model = new ArticleModel(db.findArticleWithTitle(this.field.getText().toUpperCase()));
        table.setModel(model);
        clear();
    }//GEN-LAST:event_articleTitleButtonActionPerformed

    private void articleAuthorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_articleAuthorButtonActionPerformed
    {//GEN-HEADEREND:event_articleAuthorButtonActionPerformed
        this.model = new ArticleModel(db.findArticlesWithAuthor(this.field.getText().toUpperCase()));
        table.setModel(model);
        clear();
    }//GEN-LAST:event_articleAuthorButtonActionPerformed

    private void readerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_readerButtonActionPerformed
    {//GEN-HEADEREND:event_readerButtonActionPerformed
        this.model = new ReaderModel(db.findReaderWithID(Long.parseLong(this.field.getText())));
        table.setModel(model);
        clear();
    }//GEN-LAST:event_readerButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnButtonActionPerformed
    {//GEN-HEADEREND:event_returnButtonActionPerformed
        okNotOk.setText(db.returnABook(Long.parseLong(this.field.getText())));
    }//GEN-LAST:event_returnButtonActionPerformed

    private void fieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fieldActionPerformed
    {//GEN-HEADEREND:event_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldActionPerformed

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_borrowButtonActionPerformed
    {//GEN-HEADEREND:event_borrowButtonActionPerformed
        String[] IDs = this.field.getText().split(",");
        String message = db.borrowABook(Long.parseLong(IDs[0]), Long.parseLong(IDs[1]));
        okNotOk.setText(message);
        //table.setModel(model);
    }//GEN-LAST:event_borrowButtonActionPerformed

    public void clear()
    {
        okNotOk.setText(" ");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainWindow(db).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QueryLabel;
    private javax.swing.JButton articleAuthorButton;
    private javax.swing.JLabel articleLabel;
    private javax.swing.JButton articleTitleButton;
    private javax.swing.JButton bookAuthorButton;
    private javax.swing.JLabel bookLabel;
    private javax.swing.JButton bookTitleButton;
    private javax.swing.JButton borrowButton;
    private javax.swing.JLabel explanationLabel;
    private javax.swing.JTextField field;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel okNotOk;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JButton readerButton;
    private javax.swing.JLabel readerLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
